name: build-and-test

on: push

jobs:

  buildandtest:

    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Installin
      run: |
          apt install valgrind
          pip install cpplint
	
    - name: Test them all
      run: make all -C Lab3/
